version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
  commands:
   - pip install wheel==0.45.1

python:
  install: 
    - requirements: docs/requirements.txt
    - requirements: requirements/requirements_basic.txt

sphinx:
  configuration: docs/source/conf.py
