name: cell_exploration_ml
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.10
  - pyqt=5.15
  - dask=2023
  - xarray=2023
  - scikit-learn=1.3
  - scikit-image=0.22
  - matplotlib=3.8
  - pyqtgraph=0.13
  - zarr
  - pytorch::pytorch
  - ipykernel
  - tqdm
  - mayavi
  - pip:
    - local-attention