[build-system]
requires = [
    "setuptools>=42",
    "numpy==1.26.1",
    "wheel==0.45.1",
    "vtk==9.3.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "CalTrig"
version = "0.1.0"

[tool.sphinx]
source-dir = "docs"
build-dir = "docs/_build"